import { StyleSheet,Dimensions } from "react-native";
const { width,height }=Dimensions.get('window')
const Styles=StyleSheet.create({
    mainImage:{
        width: "100%",
        height:height/2,
        flexDirection:'column',
        justifyContent:'space-between',
        alignItems:'center',
        },
    container:{
        margin:32,
    },
    buttonContainer:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        width:'100%',
    },
    buttons:{
        backgroundColor:'white',
        width:42,
        height:42,
        alignItems:'center',
        justifyContent:'center',
        borderRadius:50,
        margin:16,
    },
    miniImg:{
        width:40,
        height:40,
        margin:8,
        borderRadius:10,
    },
    footer:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'rgba(256,256,256,0.35)',
        borderRadius:15,
        margin:16,
        paddingHorizontal:8,
    },
    lastImageContainer:{
        position:'relative',
    },
    lastImage:{
        position:'absolute',
        top:8,
        left:8,
    backgroundColor:'rgba(0, 0, 0, 0.38)',
    width:40,
    height:40,
    borderRadius:10,
    },
    lastImageText:{
        position:'absolute',
        zIndex:10000,
        fontSize:20,
        color:'white',
        fontWeight:'700',
        top:'27%',
        left:'25%',
    },
    textContainer:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        marginTop:48,
    },
    titleContainer:{
        flexDirection:'column',
        gap:16,
    },
    main:{
        fontSize:32,
        fontWeight:'700',
        color:'#000000',
    },
    city:{
        fontSize:20,
        fontWeight:'500',
        color:'#000000',
    },
    icon:{
        width:42,
        height:42,
        borderRadius:21,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'rgba(244, 244, 244, 1)',
    },
    detailsContainerSecondary:{
        flexDirection:'row',
        gap:12,
        justifyContent:'center',
        alignItems:'center',
    },
    detailsContainer:{
        flexDirection:'column',
        alignItems:'flex-start',
        justifyContent:'center',
        gap:35,
        marginTop:17,
    },
    detail:{
        fontWeight:'500',
        fontSize:12,
        color:'rgba(0,0,0,1)',
        maxWidth:width-113,
    },
      map: {
        height: 300,
        width: '100%',
        paddingVertical:100,
        borderRadius:15,
    },
})
export default Styles;